const validSuperheros = [

    {
      name: 'CAPTAIN AMERICA',
      alias: 'Steve Rogers',
      affiliation: 'Avengers',
      heightCm: 185,
      isMutant: false,
      race: 'human',
      universe: 'Marvel',
      releaseYear: 1941,
    },
    {
      name: 'WOLVERINE',
      alias: 'James Howlett',
      affiliation: 'X-Men',
      heightCm: 161,
      isMutant: true,
      race: 'human',
      universe: 'Marvel',
      releaseYear: 1982,
    },
    {
      name: 'THOR',
      alias: 'God of Thunder',
      affiliation: 'Avengers',
      heightCm: 190,
      isMutant: false,
      race: 'asgard',
      universe: 'Marvel',
      releaseYear: 1978,
    },
    {
      name: 'SUPERMAN',
      alias: 'Clark Kent',
      affiliation: 'Justice League',
      heightCm: 191,
      isMutant: false,
      race: 'kryton',
      universe: 'DC',
      releaseYear: 1978,
    },
    {
      name: 'RANDOM NAME',
      alias: 'random alias',
      affiliation: 'Justice League',
      heightCm: 150,
      isMutant: false,
      race: 'random',
      universe: 'DC',
      releaseYear: 2021,
    },
    // example invalid seed data:
    // {
    //   name: 'not valid',
    //   alias: 's',
    //   affiliation: 'Avengers',
    //   heightCm: 220,
    //   isMutant: null,
    //   race: 'ASGARD',
    //   universe: 'DC',
    //   releaseYear: 1978,
    // },

  ];
