"""creating table

Revision ID: 171e3917757d
Revises:
Create Date: 2023-06-10 12:24:50.510692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171e3917757d'
down_revision = None
branch_labels = None
depends_on = None
print("IN VERSION")

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("IN VERSION UPGRADE")
    op.create_table('simple_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simple_people')
    # ### end Alembic commands ###
