-------------------------- Query --------------------------
-- From the albums, select: title, num_sold, year
-- Where the year is between 2010 and 2020.
-- Then order by the album's year (ascending), if they are the same, then num_sold (ascending)
