"""create_likes_table

Revision ID: be533b8e6c98
Revises: f5421a2cda45
Create Date: 2022-12-17 13:14:01.891263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be533b8e6c98'
down_revision = 'f5421a2cda45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('tweets', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tweets'], ['tweets.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users', 'tweets')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###