-- Select: the album's title, the band's name, and albums's num_sold 
-- after joining the two tables together through the foreign key on albums table.
-- get on the records where the number of album sold is greater than 20000
